.travis.yml, Dockerfile, Makefile, buildscripts/push, cmd/exporter/main.go, cmd/exporter/main_test.go, pkg/clientset/v1alpha1/api.go, pkg/util/scrapecr.go
- Adds travis CI for chaos-exporter along with Makefile & buildscripts
Signed-off-by: ksatchit <karthik.s@openebs.io>
=> (chore)ci: add ci for chaos exporter

cmd/exporter/main.go, pkg/chaosmetrics/scrapecr.go
- Add comments, rename variables, function and package
Signed-off-by: ksatchit <ksatchit@mayadata.io>
=> (refactor)exporter: update package, function names and comments

cmd/exporter/main.go, pkg/chaosmetrics/scrapecr.go, pkg/version/kubernetesVersion.go
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
=> Removed Comments for BetterCodeHub score(6/10 -> 7/10)

README.md
Signed-off-by: Ajesh Baby <ajesh.baby@mayadata.io>
=> Adding BCH

.gitignore, pkg/version/kubernetesVersion.go, pkg/version/kubernetesVersion_test.go
update .gitignore
add unit test for ketting k8s version
Signed-off-by: Shovan Maity <shovan.cse91@gmail.com>
=> (test) UT: Add unit test for getting k8s version

.travis.yml
Signed-off-by: Raj <mail.rajdas@gmail.com>
=> adding build script to travis

.travis.yml
* Cherry Picking commit 
Signed-off-by: Raj <mail.rajdas@gmail.com>
=> Cherry Picking from master to v0.8.x

LICENSE, cmd/exporter/main.go, cmd/exporter/main_test.go, controller/controller.go, controller/scrape.go, controller/types.go, pkg/version/kubernetesVersion.go, pkg/version/kubernetesVersion_test.go, pkg/version/openebsVersion.go, pkg/version/openebsVersion_test.go, tests/bdd/bdd_test.go
Signed-off-by: chandan kumar <chandan.kr404@gmail.com>
Issue reference: https://github.com/litmuschaos/litmus/issues/950
=> (license): Update license field in the required files

README.md
- Add the GoReport badge to README
Signed-off-by: ksatchit <ksatchit@mayadata.io>
=> (chore)badge: add a goreport badge to chaos-exporter repo

.gitlab-ci.yml
Signed-off-by: Udit Gaurav <uditgaurav@gmail.com>
- Add the baseline stage in the gitlab pipeline to record the commits in the baseline file.
=> (feat): Add the baseline stage in the gitlab pipeline

.gitlab-ci.yml
Signed-off-by: Udit Gaurav <uditgaurav@gmail.com>
- Fixing the Gitlab-ci YAML stages
=> (fix): Fixing the Gitlab-ci YAML stages

cmd/exporter/main.go
- (fix) ignore application UUID for infra chaos (#44)
Signed-off-by: ksatchit <ksatchit@mayadata.io>
=> [Cherry-pick for RC2]

NOTICE.md
- Add the license notice for chaos-exporter
Signed-off-by: ksatchit <ksatchit@mayadata.io>
=> (chore)notice: add license notice 

.travis.yml, Makefile
Signed-off-by: Raj <raj.das@mayadata.io>
- Changing installation commands of trivy
=> (Refact): Changing installation commands of trivy

Makefile
- Fixes travis build's failure to push docker images
Signed-off-by: ksatchit <karthik.s@mayadata.io>
=> (fix)ci: typo in make target

README.md, contributing.md, deploy/chaos-exporter.yaml
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
=> (chore) Added proper Documentation for updated chaos-exporter

tests/bdd/bdd_test.go
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
=> (fix)bdd : Fixed BDD URL issues

Makefile, README.md, contributing.md, deploy/chaos-exporter.yaml, tests/bdd/bdd_test.go
Cherry-picked commit:
- (fix)ci: typo in make target (#55) …
- (chore) Added proper Documentation for updated chaos-exporter (#56) …
=> Cherry pick for v1.3.x

README.md, cmd/exporter/main.go, controller/types.go, tests/bdd/bdd_test.go
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
=> (chore) Update README.md with small refactoring

prometheus/Dockerfile, prometheus/prometheus.yml
Signed-off-by: Raj Das <mail.rajdas@gmail.com>
- Refactoring prometheus.yml
=> Refactoring prometheus.yml

tests/bdd/bdd_test.go
Signed-off-by: ksatchit <karthik.s@mayadata.io>
=> (fix)bdd: update operator manifest url

tests/bdd/bdd_test.go
Signed-off-by: ksatchit <karthik.s@mayadata.io>
=> (fix)bdd: update operator manifest url (#70)

.github/workflows/release.yml
Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>
=> feat/ Add auto-release using github actions

.github/workflows/release.yml
Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>
=> Add workflow_dispatch for release in chaos exporter

Dockerfile, Makefile
Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>
=> chore(Fix): Fix Dockerfile CMD to take variables

.github/workflows/push.yml
Signed-off-by: ksatchit <karthik.s@mayadata.io>
=> (chore)workflows: add docker cred as env to push script in workflow

.github/workflows/push.yml, .github/workflows/release.yml, Makefile, README.md
minor fix in github workflow
Signed-off-by: rajdas98 <mail.rajdas@gmail.com>
=> minor fix in github workflow (push script)

README.md, controller/controller.go
Signed-off-by: shubhamchaudhary <shubham@chaosnative.com>
- Adding metrics details inside the README
=> docs(README): Adding metrics details inside the README

README.md, controller/collect-data.go, controller/controller.go, controller/handle-result-deletion.go, controller/scrape.go, controller/types.go, deploy/chaos-exporter.yaml, tests/bdd/bdd_test.go
It consists following commits:
- 0a6fadf4674508cb2102052d66de80c4aa5c2740
- c4f8170cf7dad2f15413a9bfa026e6b8a5c1b307
- 316f0cdb034203e3f66024b102a1c6d82bfe1171
- e4c45ccd2fc4fa7394a4ed0c739dafa7e183d656
=> [cherrypick for 1.13.3]

README.md
Signed-off-by: shubhamchaudhary <shubham@chaosnative.com>
Adding the litmuschaos_experiment_verdict details
=> update(readme): Adding the litmuschaos_experiment_verdict details

controller/collect-data.go, controller/handle-result-deletion.go, controller/scrape.go, controller/types.go, tests/bdd/bdd_test.go
Signed-off-by: shubhamchaudhary <shubham@chaosnative.com>
=> [Cherry-pick for 1.13.6]

README.md, controller/collect-data.go, controller/scrape.go
Signed-off-by: shubham chaudhary <shubham@chaosnative.com>
=> (engine): exporting metrics for active engine only

README.md, controller/collect-data.go, controller/controller.go, controller/scrape.go, controller/types.go, deploy/chaos-exporter.yaml
It consists following commits:
- 75ee79a2d416c6936dd8c9ee33d52e7e53c24fd8
- 01cd6a7baf2039962630cfe13137c90f38b0319b
=> [Cherrypick for 2.1.0]

.github/workflows/build.yml, .github/workflows/push.yml, .github/workflows/release.yml, controller/collect-data.go
Signed-off-by: ispeakc0de <ashubham314@gmail.com>
**Checklist:**
=> fix(verdict): fix the verdict metrics

.github/workflows/build.yml
Signed-off-by: uditgaurav <udit@chaosnative.com>
- Fixes snyk security scan on chaos-exporter
**Checklist:**
-   [ ] Commit has …
=> Chore(snyk): Fixes snyk security scan on chaos-exporter

Dockerfile
Signed-off-by: uditgaurav <udit@chaosnative.com>
**Checklist:**
=> Chore(build): Fix the go build by providing -buildvcs=false flag

controller/collect-data.go, controller/handle-result-deletion.go, controller/scrape.go, controller/types.go, go.mod, go.sum, tests/bdd/bdd_test.go
=> chore(filter): Adding the fault name filter inside all the metrics

Makefile
=> fixing the docker buildx

Makefile
=> fixing the docker buildx progress arg

.github/workflows/build.yml, .github/workflows/push.yml, .github/workflows/release.yml
=> Added K3S cluster for tests in push/release pipelines

tests/bdd/bdd_test.go
=> fix the chaoshub fault url
